// scripts/build-locales.mjs
// Composes src/i18n/messages.generated.js from the per-component translation
// files the extraction agents wrote to src/i18n/generated/<namespace>.json.
// Each JSON file is { nl: {...}, en: {...} }; the filename is the namespace.
import fs from 'node:fs'
import path from 'node:path'

const GEN_DIR = 'src/i18n/generated'
const OUT = 'src/i18n/messages.generated.js'

const nl = {}
const en = {}

const files = fs.existsSync(GEN_DIR)
  ? fs
      .readdirSync(GEN_DIR)
      .filter((f) => f.endsWith('.json'))
      .sort()
  : []

for (const f of files) {
  const ns = f.replace(/\.json$/, '')
  const data = JSON.parse(fs.readFileSync(path.join(GEN_DIR, f), 'utf8'))
  if (data.nl && Object.keys(data.nl).length) nl[ns] = data.nl
  if (data.en && Object.keys(data.en).length) en[ns] = data.en
}

const banner =
  '// AUTO-GENERATED by scripts/build-locales.mjs from src/i18n/generated/*.json\n' +
  '// Do not edit by hand. Run `node scripts/build-locales.mjs` to regenerate.\n'

fs.writeFileSync(OUT, `${banner}export default ${JSON.stringify({ nl, en }, null, 2)}\n`, 'utf8')

console.log(`✅ Composed ${OUT} from ${files.length} namespace(s): ${Object.keys(nl).join(', ')}`)
